require 'test/unit'
require 'appium_lib'
require 'testcentricity_web'

require 'testcentricity/version'
require 'testcentricity/data_objects/environment'

require 'testcentricity/app_core/appium_connect_helper'
require 'testcentricity/app_core/screen_objects_helper'
require 'testcentricity/app_core/screen_object'
require 'testcentricity/app_core/screen_section'

require 'testcentricity/app_elements/app_element_helper'
require 'testcentricity/app_elements/button'
require 'testcentricity/app_elements/checkbox'
require 'testcentricity/app_elements/label'
require 'testcentricity/app_elements/switch'
require 'testcentricity/app_elements/textfield'
require 'testcentricity/app_elements/list'
require 'testcentricity/app_elements/image'
require 'testcentricity/app_elements/select_list'
require 'testcentricity/app_elements/alert'
