
User_creds:
  valid_data:
    username: 'bob@example.com'
    password: '10203040'
  invalid_user:
    username: 'iggy.snicklefritz@example.com'
    password: '10203040'
  locked_account:
    username: 'alice@example.com'
    password: '10203040'
  no_username:
    password: '10203040'
  no_password:
    username: 'bob@example.com'
